### ISSUE TITLE
扬帆启程——软件配置管理工具git

### ISSUE THREAD

**Issue by Epsirom** [liuq880077/popush#1]
repo: https://github.com/Epsirom/popush2
Group members: @yl-1993 (杨磊2011013256) @FanChuang (庄晨帆2011013246) @Epsirom (陈华榕2011013236) @wenqf11 (文庆福2011013239) @wheiniLin (林维妮2013400888)
- 任务1：调整页面风格
  - Commit: https://github.com/Epsirom/popush2/commit/1bdd5f47e6c2eac7d2fb6ea0f4b9010cbea40428
  - Contributors: @FanChuang @Epsirom
- 任务2：登录/注册输入提示
  - Commit: https://github.com/Epsirom/popush2/commit/a97135de8b41686972a9e93fa10586c9a06576b5
  - Contributors: @yl-1993 @FanChuang
- 任务3：英文界面支持
  - Commit: https://github.com/Epsirom/popush2/commit/41c178db041202f88c5f51746fcd3f927ba23991
  - Contributors: @yl-1993 @Epsirom
- 任务4：在Ubuntu下运行
  - Commit: 文庆福2011013239
  - Contributors: @wenqf11 @yl-1993
- 任务5：在Windows下运行
  - Commit: 陈华榕2011013236
  - Contributors: @Epsirom
- 其他
  - @wheiniLin 学习HTML与CSS
  - @wenqf11 按要求发表技术博客

**Comment by ghost** [comment]
a bug was found by accident - -

**Comment by Epsirom** [comment]
@situ1992 good job...

**Comment by qiankanglai** [comment]
- ![qq20131002192032](https://f.cloud.github.com/assets/1546130/1252816/ae4a1d76-2b54-11e3-85bf-2208d22a579d.png) 拼写麻烦再检查仔细点
- 进入编辑界面之后没有修改语言的地方了？（ps.这种一般会做在设置里，而且用下拉菜单之类的会好一些）

其它做的都蛮好的。
(有些地方翻译的细节可以参考已有的英文软件，不然感觉怪怪的；换肤锁死后面的时候注意整个节目暗调)

**Comment by Epsirom** [comment]
我猜这个issue可以关闭了。

**Comment by qiankanglai** [comment]
你猜

功能OK，希望再漂亮点

**Comment by Epsirom** [comment]
看起来时间来不及了……请自行修改static_sailon文件夹为static，并复制原static中的faces和images等文件夹到static_sailon/app中，以保证头像等的正常显示:)
此外，请将nginx的root配置为static_sailon/app

**Comment by Epsirom** [comment]
为方便检查，请使用这次commit：https://github.com/Epsirom/popush2/commit/0437c1690f7e7888a185776bd866ea9c10b8f83e
这次commit只是修改了目录结构并更新Makefile等，并未做其他任何改动，以方便检查:)

**Comment by ghost** [comment]
@Epsirom 这样算迟交的哦

**Comment by Epsirom** [comment]
@situ1992 你可以检查前一个
