### ISSUE TITLE
one more night ------ 软件配置管理工具git

### ISSUE THREAD

**Issue by tzw11** [liuq880077/popush#10]
地址：https://github.com/tzw11/work
1.每个小组成员的最新commit为最终版本，项目1-3未合并

2.小组成员：黄曦，唐志伟，邱实，雒飞

任务一：邱实
任务二：雒飞
任务三：唐志伟
任务四：黄曦
任务五：唐志伟

**Comment by ghost** [comment]
oops...

**Comment by qiankanglai** [comment]
- 你们的README.md很奇怪？
- 你们的app.js呢……
- commit里有空的，以及看不懂什么意思的log

**Comment by tzw11** [comment]
助教好，按照代码上传要求重新上传了最终版本，地址：https://github.com/tzw11/tough

**Comment by qiankanglai** [comment]
没找到切换英文的地方。。。

**Comment by tzw11** [comment]
一开始在登陆注册的页面里，在logo的旁边，页面的右上侧

**Comment by tzw11** [comment]
蓝色的大字，应该蛮明显的呀~

**Comment by ghost** [comment]
@qiankanglai 他们组把代码放到了 https://github.com/tzw11/tough = =

**Comment by qiankanglai** [comment]
对啊..我是下的tough里面的，估计是没刷新。。。
