### ISSUE TITLE
死线------ 软件配置管理工具git

### ISSUE THREAD

**Issue by duanruiqi** [liuq880077/popush#11]
地址：https://github.com/duanruiqi/Popush_Modified
检查版本为最新的  kangshu

小组成员：段瑞琪 康荣 胡小强 郑灿彬 黄雅冠

段瑞琪 中英文切换
康荣 界面修改
胡小强  登录 注册提示框
黄雅冠   windows 部署
郑灿彬 linux 部署

**Comment by ghost** [comment]
quite good...

**Comment by qiankanglai** [comment]
我和@situ1992 都找不到切换中英文的地方了~ ======>OK找到了。。。只在登录界面上而且不显眼-。-其它内容问题不大

以及在网页中使用自带字体是比较忌讳的一个事情，况且这字体不适合放网页……

**Comment by qiankanglai** [comment]
背景图不够长，屏幕大的时候下半截留白了
