### ISSUE TITLE
不约而同------ 软件配置管理工具git

### ISSUE THREAD

**Issue by mayinglun** [liuq880077/popush#12]
地址：https://github.com/mayinglun/rebuild-popush
检查版本为最新的 mayinglun
(昨天网络学堂提交了，没有写issue)

小组成员：马英伦 杨植 刘汝圣 高鹏 刘谦

刘汝圣 界面修改
高鹏 登录提示框
刘谦 中英文切换
马英伦 windows 部署
杨植 linux 部署

**Comment by qiankanglai** [comment]
- 一些翻译的细节注意（密码password；注册register）这些你们平时用英文软件、网站的时候多注意积累……
- 注册时，在“用户名”框的右侧提示用户名规范“只能包含字母和数字”。。。没看到
- ![qq20131002214830](https://f.cloud.github.com/assets/1546130/1253687/680a1310-2b69-11e3-920e-0934f9951ad8.png) 类似的乱码有一些

**Comment by mayinglun** [comment]
翻译问题和乱码已修正，至于用户名规范提示，当点击用户名框时，会在下面自动显示，见最近的mayinglun

**Comment by flyawayTHU** [comment]
你们组的linux部署文档有提交么？

**Comment by qiankanglai** [comment]
点了切换到英文跳转到index2.html？

用户名框的提示是在注册不是在登录。。。
