### ISSUE TITLE
第二次作业提交——死线小组

### ISSUE THREAD

**Issue by duanruiqi** [liuq880077/popush#13]
地址：https://github.com/duanruiqi/Popush_Modified
检查的commit为Remove unnecessary files 

小组成员：段瑞琦 康荣 胡小强 郑灿彬 黄雅冠

修正了排版错误，
加强了中英切换功能（在任何一个页面均可切换），
美化了界面（调整了页面布局，增加了换肤功能），
加强了chrome下的表现

**Comment by qiankanglai** [comment]
同一次作业只用一个issue，这个关了。
