### ISSUE TITLE
【Update】扬帆启程——软件配置管理工具git

### ISSUE THREAD

**Issue by Epsirom** [liuq880077/popush#14]
repo: https://github.com/Epsirom/popush2
Group members: @yl-1993 (杨磊2011013256) @FanChuang (庄晨帆2011013246) @Epsirom (陈华榕2011013236) @wenqf11 (文庆福2011013239) @wheiniLin (林维妮2013400888)
- Commit: https://github.com/Epsirom/popush2/commit/888211d4a5c58eb5d7418c1de5ec8a948a2b60d3
- 重点改进：
  - 修复BUG
  - 翻译和换肤功能的重新实现
  - 更好的翻译
  - 细节优化

**Comment by qiankanglai** [comment]
同一次作业只用一个issue，这个关了。
