### ISSUE TITLE
【Update】一盆小铜钱——软件配置管理工具git

### ISSUE THREAD

**Issue by GrassSunFlower** [liuq880077/popush#15]
repo: https://github.com/GrassSunFlower/mypopush

Group members: @Hahehi-1 (黄怀毅 2011013264) @xiaochaowei (肖超玮 2011013279) @STZhang (张舒彤 2011013243) @opassion (张世钱 2011013227) @GrassSunFlower (陈鹏飞 2011013277)

修改与改进：
字体更改
localStorage的bug修复（导致页面崩溃的源头）
编写文件时登出footer消失的bug修复
用户注册实时提示用户名规范

**Comment by qiankanglai** [comment]
同一次作业只用一个issue，这个关了。
