### ISSUE TITLE
【Update】我们都是水果——软件配置管理工具git

### ISSUE THREAD

**Issue by silunw** [liuq880077/popush#17]
repo: https://github.com/SilunWang/popush-fruits
Contributors: @SilunWang @jianglinnan @ouyangfangxin11 @hongyu19930808 @xu-wang11
Commit: f48a491446e9daac32af2923d6e8fd297dbe102b

假期期间更新版本较多，重点改进：
1. 修复切换中英界面Bug，无须刷新页面，润色了语言翻译
2. 增加几套皮肤选择，全面重载Bootstrap，左下角增添美观选择按钮，修复页面缩放
3. 完善注册框、智能提示提升用户体验
4. 修复原项目Bug 你懂得～@situ1992

**Comment by qiankanglai** [comment]
同一次作业只用一个issue，这个关了。
