### ISSUE TITLE
快乐柿纸——项目一提交

### ISSUE THREAD

**Issue by chenlu11** [liuq880077/popush#18]
Commit：
https://github.com/hjwdzh/popush  master分支最新版本

Members: 
@hjwdzh(黄经纬 2011013234)
@gdh1995(宫大汉 2011013255) 
@ptx9363(潘天翔 2011013233)
@wangxiaoyou11(王肖佑 2011013273)
@chenlu11(陈璐 2011013249)

代码结构见/static/Readme.txt

**Comment by qiankanglai** [comment]
- 应该有的一个换行符不见了
  ![bug1](https://f.cloud.github.com/assets/1546130/1506775/6e9230e6-4946-11e3-9f92-ed36540d9ef0.jpg)
- 按钮没对齐（这个样子你们不觉得有点奇怪么……）
  ![screen shot 2013-11-09 at 21 56 40](https://f.cloud.github.com/assets/1546130/1506777/dd096bfc-4946-11e3-974a-a52f55ee8d01.png)
- chrome下有时候很容易出现socket连接不上，无法登录，刷新后被弹出。safari下无该问题。
  ![screen shot 2013-11-09 at 22 03 48](https://f.cloud.github.com/assets/1546130/1506782/e6e2800e-4947-11e3-9010-e77bd830ad1e.png)
- 文件下载功能chrome下可以,safari不行
