### ISSUE TITLE
子夜吴歌——项目一提交

### ISSUE THREAD

**Issue by hnkfyjb** [liuq880077/popush#19]
代码：https://github.com/hnkfyjb/popush master分支下的最新代码
具体说明见wiki页
提交版本以12点以前的最后commit版本为准，之后commit为bug修正。
meteor框架与原程序不兼容，实现了一个协同编辑框，在meteor分支下，请助教查阅。

**Comment by qiankanglai** [comment]
- 你们的github根本没用起来，没有历史信息，大量垃圾文件（bin啊，popush2.css~这种都有），我甚至无法区分谁做了什么
- 登录之后，切换语言菜单点了无效；刷新之后丢失
- 刷新之后，原来的有东西的文件列表变空了
- 页面交互感觉很有问题……例如（我还什么没填呢）
  ![screen shot 2013-11-09 at 23 25 21](https://f.cloud.github.com/assets/1546130/1506878/353f6464-4953-11e3-8614-8f82ad8ecfe1.png)

【话说你们最后提交的到底是meteor分支还是master分支？】

**Comment by qiankanglai** [comment]
以及，我努力的找了下但是没找到你们组写的代码文件是哪几个……一下commit上来的都是一堆node_modules，assets之类的

**Comment by hnkfyjb** [comment]
助教：
    您好！
    我们已在文档里说明，我们F5刷新是个bug，修改密码部分功能是是实现了，只是提示没有写好，还有我们第二个页面的切换语言原本是有用的，但是加了logout功能后，突然没用了，当时deadline也没有时间改正了。这些我们在文档里都说明了。

```
另外。我们最后提交的代码也是太急了，就没有删去没用的东西，这点很抱歉，我们写的代码为static里的partial以及js/ng-action，我们在文档里也有对代码的说明。
我们提交的是master分支，meteor分支只是一个附加的展示性功能，我们原本打算使用meteor重构部分后端，但是因为其与mongodb数据库耦合度较高，无法与原有工程结合。所以只是使用meteor框架写了一个协同编辑框作为尝试也放在了工程中。
```

祝好！

**Comment by hnkfyjb** [comment]
还有我们github上的master分支只有我们最后提交的东西，我们真正开发时用的是master下的各分支版本，历史信息之类的都在这些branch里面
