### ISSUE TITLE
难缠的妹纸——软件配置管理工具git

### ISSUE THREAD

**Issue by KerrTHU** [liuq880077/popush#2]
repo: https://github.com/KerrTHU/SEProject

Group members: @chucq11 (储超群 2011013225) @PomeloTea (陈琛 2011013232) @yuanhao10 (袁灏 2011013237) @BryantWang (王聪 2011013238) @KerrTHU (蔺可 2011013271)

Commit:  KerrTHU/SEProject@28eeba78f2f667ed8ac7b804bc5aa0a1f9155347
1. 我们只提交了这次作业的完整版，可直接在此版本中检查前三个任务；
2. Ubuntu下的配置文档与Windows下的配置文档见网络学堂上@chucq11 (储超群 2011013225) @PomeloTea (陈琛 2011013232)提交的作业附件。
- Task 1：
  - Contributors：@yuanhao10 @chucq11 @KerrTHU
- Task 2：
  - Contributors：@KerrTHU
- Task 3：
  - Contributors：@BryantWang @yuanhao10 @chucq11
- Task 4：
  - Contributors：@chucq11 @PomeloTea
- Task 5：
  - Contributor：@PomeloTea

**Comment by KerrTHU** [comment]
P.S. KerrTHU/SEProject@93e87c7ce3bc8f690582e6ac131967e6637adc64 下检查也可；
该版本在前一版本的基础上添加了documents文件夹，有Ubuntu和Windows下的部署文档和我们第二次作业的说明文档。

**Comment by ghost** [comment]
Good job!

**Comment by qiankanglai** [comment]
https://github.com/KerrTHU/SEProject/commit/28eeba78f2f667ed8ac7b804bc5aa0a1f9155347#commitcomment-4231538 这个commit把大量 **不需要的** 及 **系统相关** 的文件给提交上来了。请查阅gitignore解决。（bin/和node_modules/看一下是什么内容，想一想为什么是不需要提交的）

看你们的gitflow是一个人提交一次解决一个任务了？这……不太科学……

**Comment by qiankanglai** [comment]
- 文件界面好几个undefined
  ![qq20131002195302](https://f.cloud.github.com/assets/1546130/1252978/50c94cee-2b59-11e3-97c0-4ea91223e3d3.png)
- 代码编辑器修改主题无效
  ![qq20131002195422](https://f.cloud.github.com/assets/1546130/1252980/68191866-2b59-11e3-8b46-10129aa582b8.png)
- 英文界面下，见图
  ![qq20131002195510](https://f.cloud.github.com/assets/1546130/1252983/8748d9ba-2b59-11e3-8aa8-ea27c9003aeb.png)。右侧有个NaN？
- 见图。。。
  ![qq20131002195709](https://f.cloud.github.com/assets/1546130/1252993/d35339d6-2b59-11e3-8807-21468c51c91f.png)

ps. 当在编辑文件界面换主题，然后换皮肤，多来几下就可以复现了

**Comment by KerrTHU** [comment]
repo: https://github.com/KerrTHU/SEProject
检查版本: KerrTHU/SEProject@158a3f5741c3eeb32fe00fbe5c8647b1ac4419c8
- 本次提交修复的bug：
  - 切换语言时会出现undefined现象
  - 英文显示下register或log in会出现换行的问题
- 几点说明：
  - 关于第一次提交的又大量不需要或系统相关的文件，是因为开始时对git的使用还不太熟练，已删除这些不必要的文件。
  - 有的组员在完成第一次任务的时候并没有配置好环境，所以我们最后是在一台配置好环境的电脑上调试的，所以也就只有一个人提交了一个完整版的作业，现在大家都配置好后会真正开始使用git，以后不会出现第一次交作业时所谓的不太科学的情况。
  - 这周大家主要在学习前端MVC，代码编辑器是我们准备做但是还没有做好的部分，希望助教能够理解。

**Comment by qiankanglai** [comment]
没有做好的部分不好提交到主分支，master必须是任意时刻都**功能完整、没有bug**的。我只会在master上看，而且默认所有功能是可用的。写到一半的代码可以开一个branch来存放，等完全搞定之后合并回master。其他branch我是不会看的，例如你们可以git branch dev_CodeMirrorTheme什么的

git log我主要看一下你们每个人的贡献，以及代码质量等~其实你们可以试下在windows下写（如果不习惯的话），反正也只改前端页面。我推荐sourcetree很好用

别的功能都OK~
