### ISSUE TITLE
百年孤独---任务一提交

### ISSUE THREAD

**Issue by RYDBHKZYDGD** [liuq880077/popush#20]
代码：https://github.com/RYDBHKZYDGD/popush/
master下最新分支,可见在是12点之前提交的,但是issues发晚了

**Comment by qiankanglai** [comment]
- 为什么static/faces里面有3张图片提交上来了？
- 刷新后语言设置丢失；英文状态下：
  ![qq20131109-1](https://f.cloud.github.com/assets/1546130/1506862/944e8d7e-4951-11e3-9de4-f4819e9ab01e.png)；新建文件夹的英文叫new **folder**而不是new holder
- 登录状态下被弹出，主页变得很奇怪了

**Comment by RYDBHKZYDGD** [comment]
额...第一个问题是我们在测试上传头像,然后直接吧static给commit了...T^T
