### ISSUE TITLE
机智的程序猿——项目一提交

### ISSUE THREAD

**Issue by syb1001** [liuq880077/popush#21]
项目源码：
https://github.com/syb1001/popush2.0/tree/master
master分支最新代码

**Comment by qiankanglai** [comment]
- 你们现在的代码没法放二级目录下，因为是直接hashtag用的login之类的；这样带来的另一个问题就是，例如我在登录界面上(http://127.0.0.1/login)刷新就直接404了【这个也给我不同组之间带来比较大的麻烦……因为你们的项目必须在根目录下】
- 语言设置没有保存的样子
- 运行结果的控制台没有每次清空，数据会不断叠加的
- 编辑器的系统消息那边没有翻译好

**Comment by syb1001** [comment]
助教您好：
第一个问题，我不是很懂您的意思，但是我在登录界面刷新并不会直接404啊。。我们是错误url或者输入url直接重定向到login的
第二个问题，语言设置代码中有写cookie保存，但确实没有与用户相关联，不同的用户登录保存的语言状态是用同一个的
第三个问题，这个惭愧了，调试代码没有好好处理
第四个问题，room.js我们重构得不好，确实跟前面比较脱节，也是我们的问题
多谢助教指出问题~

**Comment by syb1001** [comment]
第一个问题可能确实是目录的问题，我们都是在根目录下做的，这个给助教的测试带来麻烦了，不好意思。
另外，我们组开发有用svn，有许多代码是我交到github上的，github上的记录不能完全体现工作量，特此说明一下~

**Comment by qiankanglai** [comment]
svn的repo及账户用邮件给我发一下~

第一个问题没事了=。=是因为我这边nginx有点蛋疼
