### ISSUE TITLE
死线小组--项目一提交

### ISSUE THREAD

**Issue by duanruiqi** [liuq880077/popush#23]
检查版本为final
组长：段瑞琦
组员：黄雅冠，康荣，胡小强，郑灿彬
感谢您的批阅~

**Comment by qiankanglai** [comment]
是这个么https://github.com/duanruiqi/popush.git   ？感觉不对啊。。。

**Comment by qiankanglai** [comment]
- node_modules这种不要提交
- 换行不见了
  ![screen shot 2013-11-10 at 0 23 08](https://f.cloud.github.com/assets/1546130/1506980/46b89262-495b-11e3-82b8-dd65eee71b33.png)
- 当我直接打开http://localhost/duanruiqi/#coding 这种页面的时候（没登陆情况下），最好能跳转出来；以及在登录情况下刷新就跪了。。。

**Comment by duanruiqi** [comment]
抱歉发issue的时候没说清楚，给钱大哥添麻烦了~~请司徒学长直接看https://github.com/duanruiqi/Popush_Modified
吧。感谢批阅~

**Comment by qiankanglai** [comment]
最后一个问题没事了=。=我这边有点蛋疼的问题
