### ISSUE TITLE
难缠的妹纸——项目一提交

### ISSUE THREAD

**Issue by KerrTHU** [liuq880077/popush#24]
repo: https://github.com/KerrTHU/SEProject

Group members: @chucq11 (储超群 2011013225) @PomeloTea (陈琛 2011013232) @yuanhao10 (袁灏 2011013237) @BryantWang (王聪 2011013238) @KerrTHU (蔺可 2011013271)

检查版本:  KerrTHU/SEProject@56b64b72a8e04437b9df29202f5de94d38079334

**Comment by qiankanglai** [comment]
- chrome下登出不能
  ![screen shot 2013-11-10 at 0 15 25](https://f.cloud.github.com/assets/1546130/1506968/364eb51a-495a-11e3-9e83-b2527555a534.png)
- safari下无法打开文件进行编辑了……
