### ISSUE TITLE
one more night 项目一提交

### ISSUE THREAD

**Issue by tzw11** [liuq880077/popush#25]
最后一个 commit 为最终版本

**Comment by qiankanglai** [comment]
- 点english version弹一个backbone是什么意思。。。
- 登录进去一片空白？
  ![screen shot 2013-11-10 at 0 32 48](https://f.cloud.github.com/assets/1546130/1506993/960a037c-495c-11e3-8dcf-3ee2244dc157.png)

**Comment by tzw11** [comment]
我刚才重新部署了一下，是正确显示的啊。有个问题是static/js里的chatmodel文件，我本地库了明明是chatmodel.js，不知道为什么同步上去会变成ChatModel.js，导致了chat窗口的问题。

**Comment by qiankanglai** [comment]
我看了下页面源代码里是全的，但是不知道为什么没有显示出来。而且如果我使用`make static`之后就直接连header都没有了，页面完全空白~你们的部署有什么特殊的地方么？

**Comment by tzw11** [comment]
没有啊，就是原来的部署方式，我又试了一遍，是好的。要不试试改html之前的commit，看看有没有效果
