### ISSUE TITLE
我们都是水果——项目一提交

### ISSUE THREAD

**Issue by silunw** [liuq880077/popush#26]
Last Edition
repo: https://github.com/SilunWang/popush-fruits
commit: SilunWang/popush-fruits@9973a71913808f6001992aa27c2c058e5f47ccdb

使用CanJS的MVC框架，封装所有页面；新增诸多功能请见答辩PPT
目录结构有很大变动，具体目录结构说明请见项目维护文档；

Members: 
@SilunWang(王思伦 2011013245) 
@jianglinnan(江林楠 2011013270) 
@hongyu19930808(洪宇 2011013260) 
@xu-wang11(王需 2011013248) 
@ouyangfangxin11(欧阳方昕 2011013250)

说明：
1. 建议使用chrome浏览器，firefox对CanJS框架支持不够好
2. 由于修改了models文件夹和app.js，请重新部署本工程，部署方法同readme
3. 部署后请重启popush和nginx服务，并清空chrome缓存
4. 上传文件仅支持zip上传；从github导入文件较慢，推荐测试URL: https://github.com/xu-wang11/Helloworld.git
5. 编译工程makefile生成的可执行文件命名规则：工程名+.out，工程明中包含.pro后缀

Thanks for  TAs.
The end ?  
...
A new start !

**Comment by qiankanglai** [comment]
希望目录不要写死从根目录开始，这样我没法把每个组都配成二级目录的=。=别的没啥……

**Comment by silunw** [comment]
....什么写死目录.....啥意思？？没看懂........囧

**Comment by qiankanglai** [comment]
就是你们载入东西的时候，例如template/*都是从/开始算的

**Comment by silunw** [comment]
嗯？template/*不应该表示相对路径吗？我们没有写绝对路径啊 老钱你在哪里找到的？
