### ISSUE TITLE
扬帆启程——项目一提交

### ISSUE THREAD

**Issue by Epsirom** [liuq880077/popush#27]
repo: https://github.com/Epsirom/popush2
Group members: @yl-1993 (杨磊2011013256) @FanChuang (庄晨帆2011013246) @Epsirom (陈华榕2011013236) @wenqf11 (文庆福2011013239) @wheiniLin (林维妮2013400888)
Commit: https://github.com/Epsirom/popush2/commit/b4c4522151114903ae27cdf7048dcdb005fe99ed
- 踩点完成～
- 谢谢各位助教老师辛苦付出和对我们的耐心指导。
- P.S.水果很好吃，蛋糕很好吃！
- 项目详情见稍后于网络学堂提交的报告与PPT:)

为方便检查，可以使用这次commit：https://github.com/Epsirom/popush2/commit/0437c1690f7e7888a185776bd866ea9c10b8f83e
这次commit只是修改了目录结构并更新Makefile等，并未做其他任何改动，以方便检查:)

**Comment by qiankanglai** [comment]
换行不见了
![screen shot 2013-11-10 at 0 23 08](https://f.cloud.github.com/assets/1546130/1507039/e77ba1e0-495f-11e3-85fa-5cda35a10512.png)

**Comment by Epsirom** [comment]
@qiankanglai 那不是我们的……右键，重新加载吧……以及，检查时需要启动我们的后端，原后端不能用。

**Comment by qiankanglai** [comment]
发错图了……
![v_n83 yvp sstqg_ib5u6w8](https://f.cloud.github.com/assets/1546130/1507781/e6a4639c-49aa-11e3-91e0-2a795d3ad584.jpg)
