### ISSUE TITLE
一盆小铜钱——软件配置管理工具git

### ISSUE THREAD

**Issue by GrassSunFlower** [liuq880077/popush#3]
repo: https://github.com/GrassSunFlower/mypopush

Group members: @Hahehi-1 (黄怀毅 2011013264) @xiaochaowei (肖超玮 2011013279) @STZhang (张舒彤 2011013243) @opassion (张世钱 2011013227) @GrassSunFlower (陈鹏飞 2011013277)

任务1：调整页面风格
Contributors: @xiaochaowei

任务2：用户名规范提示
Contributors: @opassion

任务3：英文界面支持
Contributors: @Hahehi-1

任务4：在Ubuntu下运行系统
Contributors: @STZhang

任务5：在Windows下运行系统
Contributors: @GrassSunFlower

Others:
@Hahehi-1 @xiaochaowei 组织会议，制定进度安排
@STZhang 整理会议内容
@opassion 发表技术博客
@GrassSunFlower Github技术支持
@STZhang @Hahehi-1 制定团队章程

**Comment by ghost** [comment]
oops...

**Comment by qiankanglai** [comment]
涉及localStorage的时候的时候，必须检查之前的值是否符合你们的定义！你们现在的代码是判断null就设置一个初始的

```
if(localStorage.getItem('lang') == null) localStorage.setItem('lang', 'zh-cn');
transinto[localStorage.getItem('lang')]();
```

但是如果已有的值是'us-en'之类不符合你们规范的就会有问题。我第一次运行你们的代码就因为前面的人的项目用的定义也是lang，但key和你们的不一样，导致首页直接无法显示。

以后别人是不会像助教一样去检查你们的代码为什么挂的，真遇到页面打开全白就直接关了

**Comment by qiankanglai** [comment]
登录及主界面直接显示translate()函数有问题，无法切英文。无用户名提示。
换的那个字体不是那么……美观。你们可以找找等宽细线体，用于各种IDE编程的

要加油啊还

**Comment by qiankanglai** [comment]
菜单这边还有点对齐问题 ![1](https://f.cloud.github.com/assets/1546130/1294509/a4ec5a30-3083-11e3-8f60-cbc090a340ca.png)

字体舒服多了（但其实我不建议网页换字体这种行为……）；然后刚进入代码编辑界面时候的字体既不是Bubble One又不是Tangerine，能切过去不能切回来就比较奇怪。

其他功能OK

**Comment by GrassSunFlower** [comment]
我们会继续努力的。
然后我小有个问题，“点击此处翻译成英文”这段文字改为英文会不会更好一些呢？

**Comment by qiankanglai** [comment]
对!这个细节很赞~

平常多参考一些比较成熟互联网产品:D
