### ISSUE TITLE
子夜吴歌——软件配置管理工具git

### ISSUE THREAD

**Issue by kikokikoTHU** [liuq880077/popush#4]
repo: https://github.com/hnkfyjb/popush

Group members: @kikokikoTHU (王苎圻 2011013261) @hnkfyjb (闫家宝 2011013265) @qsqw1237 (陆宏磊 2011013235) @caoy11 (曹晔 2011013257) @wzc11 (汪至诚 2011013262)

任务1：调整页面风格
Contributors: @kikokikoTHU 

任务2：用户名规范提示
Contributors: @qsqw1237

任务3：英文界面支持
Contributors: @caoy11

任务4：在Ubuntu下运行系统
Contributors: @hnkfyjb

任务5：在Windows下运行系统(我们配置了在mac下)
Contributors: @wzc11 

p.s.由于@kikokikoTHU的硬盘崩了，所以task 1的独立版本丢失了，所以就上传了和task 3整合版本的。

**Comment by ghost** [comment]
just soso...

**Comment by qiankanglai** [comment]
- 样式2的颜色比较凶残……
- 英文界面下的注册提示还是中文的
- 修改样式、中英文的放到选单里吧……而且和原有元素有点冲突
  ![qq20131002204630](https://f.cloud.github.com/assets/1546130/1253254/b16519c8-2b60-11e3-8d37-5a8d5ea3261c.png)

其他不错……（UI需要加强。。。

**Comment by qiankanglai** [comment]
- 垂直滚动条始终存在
- 代码编辑界面下英文中”正在保存“字样，左下角的会被codemirror挡住
  ![2](https://f.cloud.github.com/assets/1546130/1294534/215bc44c-3085-11e3-9181-500832955707.png)
