### ISSUE TITLE
我们都是水果——软件配置管理工具git

### ISSUE THREAD

**Issue by silunw** [liuq880077/popush#5]
repo: https://github.com/SilunWang/popush-fruits

Members: 
@SilunWang(王思伦 2011013245) @jianglinnan(江林楠 2011013270) @hongyu19930808(洪宇 2011013260) @xu-wang11(王需 2011013248) @ouyangfangxin11(欧阳方昕 2011013250)

All tasks have been accomplished.
Task1: contributor @jianglinnan 江林楠 
Task2: contributor @ouyangfangxin11 欧阳方昕
Task3: contributor @SilunWang 王思伦
Task4: 洪宇
Task5: 王需

Task1~Task3 already merged. 请查看最新commit版本

Task4请见网络学堂 @洪宇(2011013260)

Task5请见网络学堂 @王需(2011013248)

小组团队建设和技术博客URL: http://www.cnblogs.com/juicygroup/

小组任务板URL: https://trello.com/b/FWUXmrsX/popush-fruits

**Comment by ghost** [comment]
oops...

**Comment by qiankanglai** [comment]
- 屏幕宽不是我的错
  ![1](https://f.cloud.github.com/assets/1546130/1253285/5c2110ba-2b61-11e3-86b1-fd959bde1d73.png)
- 注册时，在“用户名”框的右侧提示用户名规范“只能包含字母和数字”<-没有看到啊
- 每次变换语言需要重新载入，比较。。用户体验差

**Comment by hongyu19930808** [comment]
助教您好：

关于第二条，注册时，如果用户在输入框中输入了非“字母/数字”，右侧马上会有相应提示，同时输入框变红。如果这样不合要求，我会反馈给小组其它成员。
关于第一、三条，以及主题部分当时是直接修改的bootstrap，没有支持多主题，我也会一并反馈给小组。

在 2013-10-02 20:53:41，"Kanglai Qian" notifications@github.com 写道：

屏幕宽不是我的错
注册时，在“用户名”框的右侧提示用户名规范“只能包含字母和数字”<-没有看到啊
每次变换语言需要重新载入，比较。。用户体验差

**Comment by qiankanglai** [comment]
1. 我的意思是，对于普通用户来说，你最好直接告诉他应该怎么输，而不是当他输错了才告诉他错了。你可以考虑下之前你遇到的注册是怎么样的~而且用户名这个东西本身还有长度限制，如果我输入了"aaaa"你们现在不会有提示，但点了注册又会报错，就感觉很不舒服。
2. 多主题切换这个不是要求里的。我指的是语言切换的时候那个刷新页面动作比较不爽。希望能做到页面内元素直接更新

你们要多从用户的角度，如果你来用这个东西，这么一种你会喜欢么

**Comment by hongyu19930808** [comment]
收到，我们会按照您的建议来进行相关修改~

在 2013-10-02 21:14:51，"Kanglai Qian" notifications@github.com 写道：

我的意思是，对于普通用户来说，你最好直接告诉他应该怎么输，而不是当他输错了才告诉他错了。你可以考虑下之前你遇到的注册是怎么样的~而且用户名这个东西本身还有长度限制，如果我输入了"aaaa"你们现在不会有提示，但点了注册又会报错，就感觉很不舒服。
多主题切换这个不是要求里的。我指的是语言切换的时候那个刷新页面动作比较不爽。希望能做到页面内元素直接更新

你们要多从用户的角度，如果你来用这个东西，这么一种你会喜欢么

**Comment by qiankanglai** [comment]
仿path的感觉相当不错~但是有点瑕疵
![qq20131009095308](https://f.cloud.github.com/assets/1546130/1294550/c5de9a6c-3085-11e3-94d0-f0bf2561b291.png)

其他的OK~

**Comment by silunw** [comment]
瑕疵指的是“主题”二字旋转吗？.......其实我是故意搞成这样的.....TT.....@qiankanglai

**Comment by qiankanglai** [comment]
故意不转正么……如果你是图案的话可以这么干，但是文字的话你必须保证我能方便的看懂。。。

**Comment by silunw** [comment]
好吧~我这就改，要不然就索性不转了 360度有点过于夸张.....

**Comment by qiankanglai** [comment]
你可以不放文字放图案的。。。http://www.findicons.com/

**Comment by silunw** [comment]
Last Edition
repo: https://github.com/SilunWang/popush-fruits
commit: SilunWang/popush-fruits@9973a71913808f6001992aa27c2c058e5f47ccdb

使用CanJS的MVC框架，封装所有页面；新增诸多功能请见答辩PPT
目录结构有很大变动，具体目录结构说明请见项目维护文档；

Members: 
@SilunWang(王思伦 2011013245) 
@jianglinnan(江林楠 2011013270) 
@hongyu19930808(洪宇 2011013260) 
@xu-wang11(王需 2011013248) 
@ouyangfangxin11(欧阳方昕 2011013250)

说明：
1. 建议使用chrome浏览器，firefox、opera等载入稍慢
2. 由于修改了models文件夹和app.js，请重新部署本工程，部署方法同readme
3. 部署后请重启popush和nginx服务，并清空chrome缓存
4. 上传文件仅支持zip上传；从github导入文件较慢，推荐测试URL: https://github.com/xu-wang11/Helloworld.git
5. 编译工程makefile生成的可执行文件命名规则：工程名+.out，工程明中包含.pro后缀

Thanks for  TAs.
The end ?  
...
A new start !

**Comment by silunw** [comment]
@liuq880077 @qiankanglai @situ1992 @gongyf07 @wanderseeme 
Thanks~

**Comment by hongyu19930808** [comment]
注：由于火狐浏览器对Can JS框架的‘#id keydown'形式的事件绑定支持不是很好，因此在火狐浏览器下回车键可能失效，建议还是使用chrome全面测试功能，体验更友好。
