### ISSUE TITLE
机智的程序猿——软件配置管理工具git

### ISSUE THREAD

**Issue by syb1001** [liuq880077/popush#6]
repo: https://github.com/syb1001/popush2.0

Group members: @syb1001 (宋艺博 2011013268) @wxcmonkey (王学成 2011013252) @yunqing (巩运青 2010013255) @simpleviola (吕婉琪 2011013251)

任务1：调整页面风格
Contributors: @wxcmonkey (王学成 2011013252)

任务2：用户名规范提示
Contributors: @syb1001 (宋艺博 2011013268)

任务3：英文界面支持
Contributors: @yunqing (巩运青 2010013255)

任务4：在Ubuntu下运行系统
Contributors: @simpleviola (吕婉琪 2011013251)

每个提交代码的成员仅提交了一个commit，即为最新commit。

**Comment by ghost** [comment]
need to do more...

**Comment by qiankanglai** [comment]
- 注册提示
- 登录界面没有语言切换
- 翻译要加油啊
- 切换语言菜单最好放右上角那里（中文一般不会缩写PRC。。。）

（能把你们组的美工叫出来谈心不。。。

**Comment by qiankanglai** [comment]
依然没看到注册提示，界面汉化不完全。
