### ISSUE TITLE
百年孤独——软件配置管理工具git

### ISSUE THREAD

**Issue by RYDBHKZYDGD** [liuq880077/popush#8]
repo: https://github.com/RYDBHKZYDGD/popush

1.final即为最终的commit版本

Group members: 丁一、王常旭、方鑫、贾尚坤、陈泽曦

任务1：调整页面风格
Contributors: 王常旭

任务2：登录/注册输入提示
Contributors: 丁一

任务3：英文界面支持
Contributors: 王常旭

任务4：在Ubuntu下运行
Contributors: 方鑫

任务5：在Windows下运行
Contributors: 贾尚坤

**Comment by ghost** [comment]
oops...

**Comment by qiankanglai** [comment]
你们的……项目呢……404.。。。

**Comment by RYDBHKZYDGD** [comment]
改成private了。。我们还以为你们已经检查过了，就准备在7号再交

**Comment by qiankanglai** [comment]
把几个助教加一下

**Comment by RYDBHKZYDGD** [comment]
好的，已经加了。但是最新版仍然有BUG，大概原因是有注释，所以在make deploy的时候没换行就把所有的JS全部注释掉了，还没有改掉的版本还没上传上去

**Comment by qiankanglai** [comment]
fileList里面的strings是null,然后一系列问题。。。你们加油:D

**Comment by qiankanglai** [comment]
只换了个背景色偷懒了吧。。。

**Comment by RYDBHKZYDGD** [comment]
因为讨论的结果是想把前段推掉重做，就没花精力修改。

**Comment by RYDBHKZYDGD** [comment]
还有个原因是负责修改前端的同学据说肚子疼住院了，所以前端是由我和另外两个人临时做的>_<

**Comment by qiankanglai** [comment]
也不用大改,其实光改css就能玩出不少花样的

**Comment by RYDBHKZYDGD** [comment]
额。。助教您好，为何我们组的任务三分数那么凄惨。。是因为不符合要求吗？

**Comment by qiankanglai** [comment]
一方面考虑了代码质量，另外就是翻译不完全、刷新之后语言设置没有保存这两个点，（还有一点点排版的小问题~）

再召唤下@situ1992

**Comment by RYDBHKZYDGD** [comment]
受教了。。。辛苦辛苦
