### ISSUE TITLE
快乐柿纸——软件配置管理工具git

### ISSUE THREAD

**Issue by chenlu11** [liuq880077/popush#9]
Repo: https://github.com/hjwdzh/popush

Members: 
@gdh1995(宫大汉 2011013255) 
@hjwdzh(黄经纬 2011013234)
@ptx9363(潘天翔 2011013233)
@wangxiaoyou11(王肖佑 2011013273)
@chenlu11(陈璐 2011013249)

All tasks have been accomplished.
Task1: contributor 王肖佑
Task2: contributor 黄经纬
Task3: contributor 陈璐
Task4: 宫大汉
Task5: 潘天翔

小组团队建设和技术博客URL: http://popush.diandian.com/

**Comment by ghost** [comment]
oops...

**Comment by qiankanglai** [comment]
- 一开始弹出来让选语言这个有点猎奇。。你可以默认英文，之后再界面上自由切换
- 注册时，在“用户名”框的右侧提示用户名规范“只能包含字母和数字”<=这个没看到啊

其它做的挺好的

ps. 我姓钱不是乾。。。现在还可以改:D

**Comment by hjwdzh** [comment]
钱康来：
     老钱你好~
     提示用户名规范是我做的，用tooltip提示的。你可以把鼠标放在用户名后面的输入框上，过一会就会弹出一个小提示。
      祝好！

黄经纬

Peter Huang
School of Software
Tsinghua University
Date: 2013-10-03
Add: Building Zijing 1# Room 402B
 Tsinghua University Beijing 100084
 P.R.CHINA
Tel: +86-18810305450 
E-mail: hjwdzh@gmail.com

From: Kanglai Qian
Date: 2013-10-02 21:04
To: qiankanglai/popush
CC: hjwdzh
Subject: Re: [popush] 快乐柿纸——软件配置管理工具git (#9)
一开始弹出来让选语言这个有点猎奇。。你可以默认英文，之后再界面上自由切换 
注册时，在“用户名”框的右侧提示用户名规范“只能包含字母和数字”<=这个没看到啊 
其它做的挺好的
ps. 我姓钱不是乾。。。现在还可以改:D

**Comment by qiankanglai** [comment]
英文界面下的tooltip还是中文的

**Comment by hjwdzh** [comment]
嗯，不好意思。原来在用cookie改语言的时候是好的，后来改成切换后，changelanguage()函数没有把title相关的属性给改变过来，现在已经修正了BUG。

Peter Huang
School of Software
Tsinghua University
Date: 2013-10-09
Add: Building Zijing 1# Room 402B
 Tsinghua University Beijing 100084
 P.R.CHINA
Tel: +86-18810305450 
E-mail: hjwdzh@gmail.com

From: Kanglai Qian
Date: 2013-10-09 10:16
To: qiankanglai/popush
CC: hjwdzh
Subject: Re: [popush] 快乐柿纸——软件配置管理工具git (#9)
英文界面下的tooltip还是中文的
